name: Unit Tests

on:
  push:
    branches:
      - master
      - release-v[0-9]+.[0-9]+.[0-9]+*
  pull_request:

jobs:
  # Label of the runner job
  test:
    # You must use a Linux environment when using service containers or container jobs
    runs-on: ubuntu-latest

    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.3.4

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: nightly
          target: wasm32-unknown-unknown
          override: true

      - name: Run cargo test
        uses: actions-rs/cargo@v1.0.3
        with:
          command: test
        env:
          # Tests get the pg url from the environment directly
          TEST_DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
          RUST_LOG: debug
          SMOL_THREADS: 2
